(Dialog TimeSave
    (Components
        (SubLayout Content)
        (Separator CommitSeparator)
        (PushButton TimeSaveCommitOK)
        (PushButton TimeSaveCommitCancel)
    )
    (Resources
        (TimeSaveCommitOK.Label "确定")
        (TimeSaveCommitOK.TopOffset 5)
        (TimeSaveCommitOK.BottomOffset 5)
        (TimeSaveCommitOK.LeftOffset 5)
        (TimeSaveCommitOK.RightOffset 5)
        (TimeSaveCommitOK.AttachLeft True)
        (TimeSaveCommitCancel.Label "取消")
        (TimeSaveCommitCancel.TopOffset 5)
        (TimeSaveCommitCancel.BottomOffset 5)
        (TimeSaveCommitCancel.LeftOffset 5)
        (TimeSaveCommitCancel.RightOffset 5)
        (TimeSaveCommitCancel.AttachRight True)
        (.TopOffset 5)
        (.BottomOffset 5)
        (.LeftOffset 5)
        (.RightOffset 5)
        (.DefaultButton "TimeSaveCommitOK")
        (.Label "设置")
        (.Resizeable False)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1)
                Content CommitSeparator
                (Grid
                    (Rows 1)
                    (Cols 1 1)
                    (Pos 1 1)
                    TimeSaveCommitOK
                    (Pos 1 2)
                    TimeSaveCommitCancel
                )
            )
        )
    )
)

(Layout Content
    (Components
        (CheckButton CBAutoSave)
        (CheckButton CBSaveAll)
        (Label LabelHint)
        (InputPanel InputTime)
    )
    (Resources
        (CBAutoSave.Label "自动保存")
        (CBAutoSave.AttachLeft True)
        (CBAutoSave.TopOffset 5)
        (CBAutoSave.BottomOffset 5)
        (CBAutoSave.LeftOffset 5)
        (CBAutoSave.RightOffset 5)
        (CBSaveAll.Label "保存所有")
        (CBSaveAll.AttachRight True)
        (CBSaveAll.TopOffset 5)
        (CBSaveAll.BottomOffset 5)
        (CBSaveAll.LeftOffset 5)
        (CBSaveAll.RightOffset 5)
        (LabelHint.Label "时间间隔（分钟）")
        (LabelHint.AttachLeft True)
        (LabelHint.TopOffset 5)
        (LabelHint.BottomOffset 5)
        (LabelHint.LeftOffset 5)
        (LabelHint.RightOffset 5)
        (InputTime.AttachLeft False)
        (InputTime.TopOffset 5)
        (InputTime.BottomOffset 5)
        (InputTime.LeftOffset 5)
        (InputTime.RightOffset 5)
        (InputTime.InputType 2)
        (InputTime.Columns 2)
        (InputTime.MinInteger 5)
        (InputTime.MaxInteger 60)

        (InputTime.Length 2)
        
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.TopOffset 5)
        (.BottomOffset 5)
        (.LeftOffset 5)
        (.RightOffset 5)
        (.AttachBottom True)
        (.Layout
            (Grid
                (Rows 0 0)
                (Cols 1 1)
                CBAutoSave CBSaveAll LabelHint InputTime
            )
        )
    )
)
