(Dialog MyTreeDialog
    (Components
        (SubLayout Content)
        (Separator CommitSeparator)
        (PushButton CommitApply)
        (Separator CommitSoftSeparator)
        (PushButton CommitOK)
        (PushButton CommitCancel)
    )
    (Resources
        (CommitSeparator.ResourceHints "Template:OKCancelApplyDialog.CommitSeparator")
        (CommitApply.Label "&Apply")
        (CommitApply.TopOffset 10)
        (CommitApply.BottomOffset 10)
        (CommitApply.LeftOffset 40)
        (CommitApply.RightOffset 0)
        (CommitApply.ResourceHints "Template:OKCancelApplyDialog.CommitApply")
        (CommitSoftSeparator.Orientation True)
        (CommitSoftSeparator.TopOffset 10)
        (CommitSoftSeparator.BottomOffset 10)
        (CommitSoftSeparator.LeftOffset 8)
        (CommitSoftSeparator.RightOffset 8)
        (CommitSoftSeparator.ResourceHints "Template:OKCancelApplyDialog.CommitSoftSeparator")
        (CommitOK.Label "OK")
        (CommitOK.TopOffset 10)
        (CommitOK.BottomOffset 10)
        (CommitOK.LeftOffset 0)
        (CommitOK.RightOffset 0)
        (CommitOK.ResourceHints "Template:OKCancelApplyDialog.CommitOK")
        (CommitCancel.Label "Cancel")
        (CommitCancel.TopOffset 10)
        (CommitCancel.BottomOffset 10)
        (CommitCancel.LeftOffset 8)
        (CommitCancel.RightOffset 10)
        (CommitCancel.ResourceHints "Template:OKCancelApplyDialog.CommitCancel")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.DefaultButton "CommitOK")
        (.ResourceHints "Template:OKCancelApplyDialog" "Guidelines:Creo4-Dialog" "GuidelinesVersion:2" "Version:Creo4" "@Subgrid0x2.Template:OKCancelApplyDialog.CommitBar")
        (.Accelerator "Esc")
        (.AttachLeft True)
        (.Bitmap "UI Menu Cascade unsel image")
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1)
                Content CommitSeparator
                (Grid
                    (Rows 1)
                    (Cols 1 0 0 0 0)
                    (Pos 1 2)
                    CommitApply
                    (Pos 1 3)
                    CommitSoftSeparator
                    (Pos 1 4)
                    CommitOK
                    (Pos 1 5)
                    CommitCancel
                )
            )
        )
    )
)
(Layout Content
    (Components
        (Tree MyTree)
    )
    (Resources
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.TopOffset 16)
        (.BottomOffset 16)
        (.LeftOffset 10)
        (.RightOffset 10)
        (.ResourceHints "Template:OKCancelApplyDialog.Content")
        (.AttachBottom True)
        (.Layout
            (Grid
                (Rows 1)
                (Cols 1)
                (Grid
                    (Rows 1)
                    (Cols 1)
                    MyTree
                )
            )
        )
    )
)
(TreeAttributeWindow MyTree
    (Components
        (PushButton PushButton1)
        (InputPanel InputPanel1)
    )
    (Resources
        (PushButton1.AttachLeft True)
        (PushButton1.TopOffset 0)
        (PushButton1.BottomOffset 0)
        (PushButton1.LeftOffset 0)
        (PushButton1.RightOffset 0)
        (InputPanel1.TopOffset 0)
        (InputPanel1.BottomOffset 0)
        (InputPanel1.LeftOffset 0)
        (InputPanel1.RightOffset 0)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.ListType 3)
        (.AutoOpen True)
        (.Selected_image "UI Cascade unsel image")
        (.ShowGrid True)
        (.TreeAttributeWindow True)
        (.SelectByCell True)
    )
)
